Repository cb-oss2021/oss-roadmap, pull requests merged in 2021-09, with the labels that each got.

#20 [#18] develop: frontend 로드맵 버그 수정
  src/data.js
Labels: 버그

#31 [#30]develop FAQ FrontEnd 내용 추가
  src/util/open-help.js
Labels: 기능 추가

#29 [#28] BackEnd OS 섹션 추가
  assets/backend-languages/java.svg
  assets/backend-languages/javascript.svg
  assets/basic-frontend-knowledge/css.svg
  assets/basic-frontend-knowledge/html.svg
  assets/basic-frontend-knowledge/javascript.svg
  assets/os-knowledge/io-management.svg
  assets/os-knowledge/memory-management.svg
  assets/os-knowledge/process-management.svg
  src/data.js
  src/data/backend-languages.js
  src/data/basic-frontend-knowledge.js
  src/data/os-knowledge.js
Labels: 기능 추가

#34 [#33] BackEnd 로드맵 Database 섹션 추가
  assets/backend-databases/acid.svg
  assets/backend-databases/armstrongs-axioms.svg
  assets/backend-databases/data-integrity.svg
  assets/backend-databases/data-modelling.svg
  assets/backend-databases/deadlocks.svg
  assets/backend-databases/er-diagram.svg
  assets/backend-databases/functional-dependencies.svg
  assets/backend-databases/indexing.svg
  assets/backend-databases/keys.svg
  assets/backend-databases/locks.svg
  assets/backend-databases/mongodb.svg
  assets/backend-databases/mysql.svg
  assets/backend-databases/non-relational-databases.svg
  assets/backend-databases/normal-forms.svg
  assets/backend-databases/normalization.svg
  assets/backend-databases/postgresql.svg
  assets/backend-databases/precedence-graph.svg
  assets/backend-databases/redis.svg
  assets/backend-databases/relational-algebra.svg
  assets/backend-databases/relational-databases.svg
  assets/backend-databases/serializability.svg
  assets/backend-databases/sql.svg
  assets/backend-databases/transactions.svg
  src/data.js
  src/data/backend-databases.js
Labels: 기능 추가

#35 [#2]feature:자바 스크립트 로드맵 추가
  assets/java-script/DOM/DOM.svg
  assets/java-script/DOM/core-dom.svg
  assets/java-script/DOM/dom-interface.svg
  assets/java-script/DOM/dom의-기본.svg
  assets/java-script/DOM/dom의-종류.svg
  assets/java-script/DOM/html-dom.svg
  assets/java-script/DOM/xml-dom.svg
  assets/java-script/ajax/ajax-예제.svg
  assets/java-script/ajax/ajax.svg
  assets/java-script/ajax/long-polling.svg
  assets/java-script/ajax/polling.svg
  assets/java-script/ajax/stun-nat-turn.svg
  assets/java-script/ajax/tech.svg
  assets/java-script/ajax/webRTC.svg
  assets/java-script/api/api.svg
  assets/java-script/api/hinstance.svg
  assets/java-script/api/instance.svg
  assets/java-script/api/wchar.svg
  assets/java-script/api/자료형.svg
  assets/java-script/api/자료형의-의미.svg
  assets/java-script/es6/cloud-script.svg
  assets/java-script/es6/es6.svg
  assets/java-script/es6/es6의-특징.svg
  assets/java-script/es6/ts와의-차이.svg
  assets/java-script/syntax/syntax.svg
  assets/java-script/syntax/객체.svg
  assets/java-script/syntax/기초-학습.svg
  assets/java-script/syntax/심화-학습.svg
  assets/java-script/syntax/웹에서의-역할.svg
  assets/java-script/syntax/전개-구문.svg
  assets/java-script/syntax/템플릿-리터럴.svg
  src/data/java-script.js
Labels: 기능 수정

#38 [#37]develop FAQ BackEnd 내용 추가
  src/util/open-help.js
Labels: 기능 추가

#39 [#36] bug: fix merge conflict
  src/data.js
Labels: 기능 수정

#43 [#42]develop FrontEnd Page 연결
  FrontEnd.html
  src/FrontEndCollection.js
  src/Main.js
Labels: 기능 수정

#40 [#13]feature:css,html로드맵 추가
  assets/html/basic/basic.svg
  assets/html/basic/svg.svg
  assets/html/basic/기본-틀.svg
  assets/html/basic/예제.svg
  assets/html/basic/웹-개발-학습.svg
  assets/html/basic/태그.svg
  assets/html/convention/NHN-코딩-규범.svg
  assets/html/convention/convention.svg
  assets/html/convention/html-구조.svg
  assets/html/convention/스타일-선언.svg
  assets/html/convention/자바-스크립트-선언.svg
  assets/html/form/form-태그.svg
  assets/html/form/form.svg
  assets/html/form/semantic-태그.svg
  assets/html/form/semantic.svg
  assets/html/form/폼-디자인.svg
  assets/html/seo/seo.svg
  assets/html/seo/메타-태그.svg
  assets/html/seo/색인-생성.svg
  assets/html/유효성-검사/w3c.svg
  assets/html/유효성-검사/모범사례.svg
  assets/html/유효성-검사/유효성-검사.svg
  src/data/css.js
  src/data/html.js
Labels: 기능 추가

#49 [#48]develop 화면 전환 버튼 생성
  src/BackEnd.js
  src/app.js
  src/data/FrontEnd.js
Labels: 기능 추가

#51 [#50]develop toast 코드 삭제
  src/BackEnd.js
  src/app.js
Labels: 기능 수정

#53 [#33] develop: BackEnd 데이터베이스 추가
  src/BackEndCollection.js
Labels: 기능 수정

#55 [#54] Master 브랜치 3차 병합
  src/BackEnd.js
  src/BackEndCollection.js
  src/app.js
  src/data/FrontEnd.js
Labels: 머지

#61 Issue #2, Issue #32, Issue #33 내용 수정, Issue #62 기능 추가
  assets/backend-languages/python.svg
  assets/backend-languages/ruby.svg
  assets/internet/browsers-and-how-they-work.svg
  assets/internet/what-is-domain-name.svg
  assets/internet/what-is-hosting.svg
  assets/servers/architectural-models.svg
  assets/servers/client-many-servers.svg
  assets/servers/client-server.svg
  assets/servers/crud.svg
  assets/servers/docker.svg
  assets/servers/express.svg
  assets/servers/gnu-linux.svg
  assets/servers/graphql.svg
  assets/servers/middleware.svg
  assets/servers/peer-to-peer.svg
  assets/servers/proxy-server.svg
  assets/servers/request-reply-protocol.svg
  assets/servers/rest-api.svg
  assets/servers/ssh.svg
  assets/servers/tcp.svg
  assets/servers/udp.svg
  src/BackEndCollection.js
  src/data/databases.js
  src/data/internet.js
  src/data/servers.js
Labels: 기능 추가

#72 [#52]develop:아이콘 오류 해결"
  assets/frame-work/lit-html.svg
  assets/frame-work/mobx.svg
  assets/frame-work/reactivejs.svg
  assets/frame-work/vuex.svg
  assets/html/convention/nhn-코딩-규범.svg
  assets/java-script/ajax/webrtc.svg
  assets/java-script/dom/core-dom.svg
  assets/java-script/dom/dom-interface.svg
  assets/java-script/dom/dom.svg
  assets/java-script/dom/dom의-기본.svg
  assets/java-script/dom/dom의-종류.svg
  assets/java-script/dom/html-dom.svg
  assets/java-script/dom/xml-dom.svg
Labels: 버그, 기능 수정
